services:
  - type: web
    name: clever-water
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
